### PR TITLE
Mvn central push branch

### PR DESCRIPTION
**Pull request by saifEBI**
This branch is deployable to Maven Central. It contains a settings XML with Sonnatype  credentials for my account and a passphrase for my public key.  As mentioned in a previous comment,  I'm not sure what steps we should take to make this process generic for every developer (or if that is necessary).

### CODE REVIEW

**Comment by susheel** [comment]
Option 1: Register private keys and approve registered users on JIRA Sonatype?
Option 2: Generate GPG keys for the beacon mailing type "ga4gh-beacon-technical@genomicsandhealth.org" perhaps?

**Comment by saifEBI** [comment]
Document here: 

https://github.com/ga4gh/beacon-team/wiki/Maven-Central-Repository-Deployment.

**Comment by mcupak** [comment]
I've just realized this has been submitted against `develop`. The changes should be rebased and submitted against the `develop-proto` branch in a new PR. Sorry, we should have made it clear that was the branch we were working with...

**Comment by mcupak** [comment]
@juhtornr ^^

**Comment by juhtornr** [comment]
We discussed this with @sdelatorrep and because we are going to make new release it's not worth of making new PR. Therefore I just merge this directly to develop.

**Pull request merged**
