### PR TITLE
Add CC and ADA-M to Beacon spec

### PR DESCRIPTION
**Pull request by sdelatorrep**
Implementation proposal of #22

### CODE REVIEW

**Comment by antbro** [comment]
Hi Sabela et al
Francis (who is leading the ADA-M API and related matters) and I are very happy with this
Cheers
Tony

**Comment by jdylan** [comment]
Hi All,
Can we add support for DUO also ( http://www.obofoundry.org/ontology/duo.html ) - this is based on consent codes

**Comment by antbro** [comment]
Great!
And I believe DUO was being extended to incorporate ADA-M elements as well. So we'd then have everything interconnected. Plus, the conjunction via DUO would give us a great place to work on unambiguously defining and harmonising term definitions regarding data use conditions
Cheers
Tony

________________________________________

**Comment by sdelatorrep** [comment]
I suggest creating a new issue for including DUO and placing it in the next milestone. Do you agree?

**Comment by antbro** [comment]
yes
Thanks, T

________________________________________

**Comment by sdelatorrep** [comment]
Done. New issue #111

**Comment by susheel** [comment]
TravisCI check fails as it uses [avro-schema-test](https://github.com/mcupak/avro-schema-test-base.git)

**Comment by sdelatorrep** [comment]
Hi,
Could somebody merge this PR? I can't do it. 
Thanks!

**Comment by mcupak** [comment]
CI is failing, the build should be fixed before merging.

**Comment by sdelatorrep** [comment]
But it's failing because it's using the avro-schema-test, isn't it? If so, I would disable this tests until the protobuf tests (#103) are finished and merged (although I'm not sure that working on that makes any sense if we're moving away from protobuf after v0.4).
BTW, if this is not the reason, I don't know how to fix it.

**Pull request merged**
