### PR TITLE
Add Slackin badge

### PR DESCRIPTION
**Pull request by mcupak**

### CODE REVIEW

**Comment by antbro** [comment]
Could someone explain to the group the advantages/need for this



From my understanding of Slackin Badges I struggle to see the value for Beacon, which probably means I do not understand Slackin Badges :-)



Tony







________________________________

**Comment by mcupak** [comment]
It's basically just a fancy link to the Slack signup page. We don't need it I suppose, I just thought it would be nice - if people find our repository and have a question, they can just hop on Slack.

**Comment by david4096** [comment]
+1 can we make it ga4gh wide?

**Comment by mcupak** [comment]
The Slack team? Sure, I’ll +1 that.

**Comment by mfiume** [comment]
+1

**Pull request merged**
