### PR TITLE
Beacon in protobuf

### PR DESCRIPTION
**Pull request by KyleGao**
Translation from avro to protobuf.

### CODE REVIEW

**Comment by david4096** [comment]
Could you let me know what you think of #58?

**Comment by KyleGao** [comment]
Well, it was opened and last discussed half a year ago. I wasn't in the project by then, #58 seems a legacy rather then a undergoing task to me.

**Comment by david4096** [comment]
Thanks just wondering. It seems like the avro descriptors haven't changed for longer than six months. I'm in no way attached to that PR, just wondering what changed about it.

**Comment by mbaudis** [comment]
@david4096 @KyleGao @mcupak 

We should just compare & modify & close one of those. The new PR stems from the hibernation & now just taking the current status (as Bo said, we hadn't been involved with the Beacon code dev before).

So David: Maybe you have a look & decide? We just need to forge ahead, to make protocol extensions feasible (see discussions in https://github.com/ga4gh/schemas/issues/752 and https://github.com/ga4gh/beacon-team/pull/65).

**Comment by KyleGao** [comment]
I did a diff between two PRs, and they are almost identical except the Snake/Camel cases. 
@david4096 Maybe we could have a new develop-proto branch?

**Comment by mcupak** [comment]
Thanks @KyleGao. This is good, but I think #58 provides a slightly better starting point (there are differences in a few fields + conventions). As noted in https://github.com/ga4gh/beacon-team/pull/58#issuecomment-266569452, I moved it to the [develop-proto](https://github.com/ga4gh/beacon-team/tree/develop-proto) branch for further development.

I'm closing this PR, if there's anything in particular here that you feel is not reflected in the new branch, please send a new PR against it.

**Comment by mbaudis** [comment]
Thanks @mcupak for moving this forward. And thanks @KyleGao; this was the scope ;-)

**Comment by david4096** [comment]
Fwiw, we are very much in favor to getting the beacon schemas into the mainline API. @benedictpaten @kozbo

**Pull request closed without merging**
